# Use an official Node.js runtime as a parent image
FROM node:20-alpine AS base

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock)
COPY package.json package-lock.json ./

# Install the app dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the default Next.js port
EXPOSE 3000

# Set environment variable to enable development mode
ENV NODE_ENV=development

# Start Next.js development server
CMD ["npm", "run", "dev"]
